{
  "Header": {
    "Original": "CVE-2020-14422 (Lib/ipaddress.py in Python through 3.8.3 improperly computes hash valu ...)",
    "Line": 194711,
    "ID": "CVE-2020-14422",
    "Description": "(Lib/ipaddress.py in Python through 3.8.3 improperly computes hash valu ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2280-1}",
      "Line": 194712,
      "Type": "xref",
      "Bugs": [
        "DLA-2280-1"
      ]
    },
    {
      "Original": "- python3.8 3.8.4~rc1-1",
      "Line": 194713,
      "Type": "package",
      "Package": "python3.8",
      "Kind": "fixed",
      "Version": "3.8.4~rc1-1"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Line": 194714,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "[buster] - python3.7 3.7.3-2+deb10u2",
      "Line": 194715,
      "Type": "package",
      "Release": "buster",
      "Package": "python3.7",
      "Kind": "fixed",
      "Version": "3.7.3-2+deb10u2"
    },
    {
      "Original": "- python3.5 \u003cremoved\u003e",
      "Line": 194716,
      "Type": "package",
      "Package": "python3.5",
      "Kind": "removed"
    },
    {
      "Original": "- python3.4 \u003cremoved\u003e",
      "Line": 194717,
      "Type": "package",
      "Package": "python3.4",
      "Kind": "removed"
    },
    {
      "Original": "[jessie] - python3.4 \u003cpostponed\u003e (Minor issue, DoS with constraints)",
      "Line": 194718,
      "Type": "package",
      "Release": "jessie",
      "Package": "python3.4",
      "Kind": "postponed",
      "Description": "Minor issue, DoS with constraints"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue41004",
      "Line": 194719,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue41004"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/20956",
      "Line": 194720,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/20956"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/21033",
      "Line": 194721,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/21033"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/b30ee26e366bf509b7538d79bfec6c6d38d53f28 (master)",
      "Line": 194722,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/b30ee26e366bf509b7538d79bfec6c6d38d53f28 (master)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/9a646aa82dfa62d70ca2a99ada901ee6cf9f82bd (3.9-branch)",
      "Line": 194723,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/9a646aa82dfa62d70ca2a99ada901ee6cf9f82bd (3.9-branch)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/dc8ce8ead182de46584cc1ed8a8c51d48240cbd5 (v3.8.4rc1)",
      "Line": 194724,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/dc8ce8ead182de46584cc1ed8a8c51d48240cbd5 (v3.8.4rc1)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/b98e7790c77a4378ec4b1c71b84138cb930b69b7 (3.7-branch)",
      "Line": 194725,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/b98e7790c77a4378ec4b1c71b84138cb930b69b7 (3.7-branch)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/cfc7ff8d05f7a949a88b8a8dd506fb5c1c30d3e9 (3.6-branch)",
      "Line": 194726,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/cfc7ff8d05f7a949a88b8a8dd506fb5c1c30d3e9 (3.6-branch)"
    }
  ]
}