{
  "Header": {
    "Original": "CVE-2021-30159 (An issue was discovered in MediaWiki before 1.31.12 and 1.32.x through ...)",
    "Line": 124691,
    "ID": "CVE-2021-30159",
    "Description": "(An issue was discovered in MediaWiki before 1.31.12 and 1.32.x through ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4889-1 DLA-2648-1}",
      "Line": 124692,
      "Type": "xref",
      "Bugs": [
        "DSA-4889-1",
        "DLA-2648-1"
      ]
    },
    {
      "Original": "- mediawiki 1:1.35.2-1",
      "Line": 124693,
      "Type": "package",
      "Package": "mediawiki",
      "Kind": "fixed",
      "Version": "1:1.35.2-1"
    },
    {
      "Original": "NOTE: https://phabricator.wikimedia.org/T272386",
      "Line": 124694,
      "Type": "NOTE",
      "Description": "https://phabricator.wikimedia.org/T272386"
    },
    {
      "Original": "NOTE: https://lists.wikimedia.org/pipermail/wikitech-l/2021-April/094418.html",
      "Line": 124695,
      "Type": "NOTE",
      "Description": "https://lists.wikimedia.org/pipermail/wikitech-l/2021-April/094418.html"
    }
  ]
}