{
  "Header": {
    "Original": "CVE-2022-24859 (PyPDF2 is an open source python PDF library capable of splitting, merg ...)",
    "Line": 68957,
    "ID": "CVE-2022-24859",
    "Description": "(PyPDF2 is an open source python PDF library capable of splitting, merg ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3039-1}",
      "Line": 68958,
      "Type": "xref",
      "Bugs": [
        "DLA-3039-1"
      ]
    },
    {
      "Original": "- pypdf2 1.27.9-1 (bug #1009879)",
      "Line": 68959,
      "Type": "package",
      "Package": "pypdf2",
      "Kind": "fixed",
      "Version": "1.27.9-1",
      "BugNo": 1009879
    },
    {
      "Original": "[bullseye] - pypdf2 \u003cno-dsa\u003e (Minor issue)",
      "Line": 68960,
      "Type": "package",
      "Release": "bullseye",
      "Package": "pypdf2",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - pypdf2 \u003cno-dsa\u003e (Minor issue)",
      "Line": 68961,
      "Type": "package",
      "Release": "buster",
      "Package": "pypdf2",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/PyPDF2/security/advisories/GHSA-xcjx-m2pj-8g79",
      "Line": 68962,
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/PyPDF2/security/advisories/GHSA-xcjx-m2pj-8g79"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/PyPDF2/issues/329",
      "Line": 68963,
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/PyPDF2/issues/329"
    },
    {
      "Original": "NOTE: https://github.com/py-pdf/PyPDF2/pull/740",
      "Line": 68964,
      "Type": "NOTE",
      "Description": "https://github.com/py-pdf/PyPDF2/pull/740"
    }
  ]
}