{
  "Header": {
    "Original": "CVE-2017-15922 (In GNU Libextractor 1.4, there is an out-of-bounds read in the EXTRACT ...)",
    "Line": 346948,
    "ID": "CVE-2017-15922",
    "Description": "(In GNU Libextractor 1.4, there is an out-of-bounds read in the EXTRACT ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1198-1}",
      "Line": 346949,
      "Type": "xref",
      "Bugs": [
        "DLA-1198-1"
      ]
    },
    {
      "Original": "- libextractor 1:1.6-2 (low; bug #880016)",
      "Line": 346950,
      "Type": "package",
      "Package": "libextractor",
      "Kind": "fixed",
      "Version": "1:1.6-2",
      "Severity": "low",
      "BugNo": 880016
    },
    {
      "Original": "[stretch] - libextractor 1:1.3-4+deb9u1",
      "Line": 346951,
      "Type": "package",
      "Release": "stretch",
      "Package": "libextractor",
      "Kind": "fixed",
      "Version": "1:1.3-4+deb9u1"
    },
    {
      "Original": "[jessie] - libextractor 1:1.3-2+deb8u1",
      "Line": 346952,
      "Type": "package",
      "Release": "jessie",
      "Package": "libextractor",
      "Kind": "fixed",
      "Version": "1:1.3-2+deb8u1"
    },
    {
      "Original": "NOTE: http://lists.gnu.org/archive/html/bug-libextractor/2017-10/msg00008.html",
      "Line": 346953,
      "Type": "NOTE",
      "Description": "http://lists.gnu.org/archive/html/bug-libextractor/2017-10/msg00008.html"
    },
    {
      "Original": "NOTE: Fixed by: https://git.gnunet.org/libextractor.git/commit/?id=d4d488b0e5ab13dda241d688d87a07816368f117",
      "Line": 346954,
      "Type": "NOTE",
      "Description": "Fixed by: https://git.gnunet.org/libextractor.git/commit/?id=d4d488b0e5ab13dda241d688d87a07816368f117"
    }
  ]
}