{
  "Header": {
    "Original": "CVE-2019-10208 (A flaw was discovered in postgresql versions 9.4.x before 9.4.24, 9.5. ...)",
    "Line": 263134,
    "ID": "CVE-2019-10208",
    "Description": "(A flaw was discovered in postgresql versions 9.4.x before 9.4.24, 9.5. ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4493-1 DSA-4492-1 DLA-1874-1}",
      "Line": 263135,
      "Type": "xref",
      "Bugs": [
        "DSA-4493-1",
        "DSA-4492-1",
        "DLA-1874-1"
      ]
    },
    {
      "Original": "- postgresql-11 11.5-1",
      "Line": 263136,
      "Type": "package",
      "Package": "postgresql-11",
      "Kind": "fixed",
      "Version": "11.5-1"
    },
    {
      "Original": "- postgresql-9.6 \u003cremoved\u003e",
      "Line": 263137,
      "Type": "package",
      "Package": "postgresql-9.6",
      "Kind": "removed"
    },
    {
      "Original": "- postgresql-9.4 \u003cremoved\u003e",
      "Line": 263138,
      "Type": "package",
      "Package": "postgresql-9.4",
      "Kind": "removed"
    },
    {
      "Original": "NOTE: https://www.postgresql.org/about/news/1960/",
      "Line": 263139,
      "Type": "NOTE",
      "Description": "https://www.postgresql.org/about/news/1960/"
    }
  ]
}