{
  "Header": {
    "Original": "CVE-2017-12956 (There is an illegal address access in Exiv2::FileIo::path[abi:cxx11]() ...)",
    "Line": 353568,
    "ID": "CVE-2017-12956",
    "Description": "(There is an illegal address access in Exiv2::FileIo::path[abi:cxx11]() ...)"
  },
  "Annotations": [
    {
      "Original": "- exiv2 \u003cnot-affected\u003e (Vulnerable code introduced after 0.25; only affected experimental; bug #888872)",
      "Line": 353569,
      "Type": "package",
      "Package": "exiv2",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced after 0.25; only affected experimental; bug #888872"
    },
    {
      "Original": "NOTE: https://github.com/Exiv2/exiv2/issues/59",
      "Line": 353570,
      "Type": "NOTE",
      "Description": "https://github.com/Exiv2/exiv2/issues/59"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1482296",
      "Line": 353571,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1482296"
    }
  ]
}