{
  "Header": {
    "Original": "CVE-2022-3854 [possible DoS issue in ceph URL processing on RGW backends]",
    "Line": 13373,
    "ID": "CVE-2022-3854",
    "Description": "[possible DoS issue in ceph URL processing on RGW backends]"
  },
  "Annotations": [
    {
      "Original": "RESERVED",
      "Line": 13374,
      "Type": "RESERVED"
    },
    {
      "Original": "- ceph \u003cunfixed\u003e (bug #1027151)",
      "Line": 13375,
      "Type": "package",
      "Package": "ceph",
      "Kind": "unfixed",
      "BugNo": 1027151
    },
    {
      "Original": "[bullseye] - ceph \u003cnot-affected\u003e (Vulnerable code added in Ceph 16.1)",
      "Line": 13376,
      "Type": "package",
      "Release": "bullseye",
      "Package": "ceph",
      "Kind": "not-affected",
      "Description": "Vulnerable code added in Ceph 16.1"
    },
    {
      "Original": "[buster] - ceph \u003cnot-affected\u003e (Vulnerable code added in Ceph 16.1)",
      "Line": 13377,
      "Type": "package",
      "Release": "buster",
      "Package": "ceph",
      "Kind": "not-affected",
      "Description": "Vulnerable code added in Ceph 16.1"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2139925",
      "Line": 13378,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2139925"
    },
    {
      "Original": "NOTE: https://bugzilla.suse.com/show_bug.cgi?id=1205025",
      "Line": 13379,
      "Type": "NOTE",
      "Description": "https://bugzilla.suse.com/show_bug.cgi?id=1205025"
    },
    {
      "Original": "NOTE: https://tracker.ceph.com/issues/55765",
      "Line": 13380,
      "Type": "NOTE",
      "Description": "https://tracker.ceph.com/issues/55765"
    },
    {
      "Original": "NOTE: https://github.com/ceph/ceph/pull/47025",
      "Line": 13381,
      "Type": "NOTE",
      "Description": "https://github.com/ceph/ceph/pull/47025"
    }
  ]
}