{
  "Header": {
    "Original": "CVE-2018-14659 (The Gluster file system through versions 4.1.4 and 3.1.2 is vulnerable ...)",
    "Line": 302113,
    "ID": "CVE-2018-14659",
    "Description": "(The Gluster file system through versions 4.1.4 and 3.1.2 is vulnerable ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2806-1 DLA-1565-1}",
      "Line": 302114,
      "Type": "xref",
      "Bugs": [
        "DLA-2806-1",
        "DLA-1565-1"
      ]
    },
    {
      "Original": "- glusterfs 5.1-1 (bug #912997)",
      "Line": 302115,
      "Type": "package",
      "Package": "glusterfs",
      "Kind": "fixed",
      "Version": "5.1-1",
      "BugNo": 912997
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2018/10/31/5",
      "Line": 302116,
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2018/10/31/5"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1635929",
      "Line": 302117,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1635929"
    },
    {
      "Original": "NOTE: https://review.gluster.org/#/c/glusterfs/+/21530/",
      "Line": 302118,
      "Type": "NOTE",
      "Description": "https://review.gluster.org/#/c/glusterfs/+/21530/"
    },
    {
      "Original": "NOTE: http://git.gluster.org/cgit/glusterfs.git/commit/?id=be1e1785e2e4f3d6345ea5b5b684a1429784a01c",
      "Line": 302119,
      "Type": "NOTE",
      "Description": "http://git.gluster.org/cgit/glusterfs.git/commit/?id=be1e1785e2e4f3d6345ea5b5b684a1429784a01c"
    }
  ]
}