{
  "Header": {
    "Original": "CVE-2016-9877 (An issue was discovered in Pivotal RabbitMQ 3.x before 3.5.8 and 3.6.x ...)",
    "Line": 384776,
    "ID": "CVE-2016-9877",
    "Description": "(An issue was discovered in Pivotal RabbitMQ 3.x before 3.5.8 and 3.6.x ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-3761-1}",
      "Line": 384777,
      "Type": "xref",
      "Bugs": [
        "DSA-3761-1"
      ]
    },
    {
      "Original": "- rabbitmq-server 3.6.6-1 (bug #849849)",
      "Line": 384778,
      "Type": "package",
      "Package": "rabbitmq-server",
      "Kind": "fixed",
      "Version": "3.6.6-1",
      "BugNo": 849849
    },
    {
      "Original": "[wheezy] - rabbitmq-server \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Line": 384779,
      "Type": "package",
      "Release": "wheezy",
      "Package": "rabbitmq-server",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://pivotal.io/security/cve-2016-9877",
      "Line": 384780,
      "Type": "NOTE",
      "Description": "https://pivotal.io/security/cve-2016-9877"
    },
    {
      "Original": "NOTE: https://github.com/rabbitmq/rabbitmq-mqtt/issues/96",
      "Line": 384781,
      "Type": "NOTE",
      "Description": "https://github.com/rabbitmq/rabbitmq-mqtt/issues/96"
    },
    {
      "Original": "NOTE: https://github.com/rabbitmq/rabbitmq-mqtt/pull/98",
      "Line": 384782,
      "Type": "NOTE",
      "Description": "https://github.com/rabbitmq/rabbitmq-mqtt/pull/98"
    }
  ]
}