{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ceph Storage 3",
      "fix_state": "Out of support scope",
      "package_name": "ceph",
      "cpe": "cpe:/a:redhat:ceph_storage:3"
    },
    {
      "product_name": "Red Hat Ceph Storage 4",
      "fix_state": "Affected",
      "package_name": "ceph",
      "cpe": "cpe:/a:redhat:ceph_storage:4"
    },
    {
      "product_name": "Red Hat Ceph Storage 5",
      "fix_state": "Affected",
      "package_name": "ceph",
      "cpe": "cpe:/a:redhat:ceph_storage:5"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2022-11-10T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2022-3931 Rook Ceph crashcollector: Container breakout",
    "id": "2141733",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2141733"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.7",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:N/S:C/C:H/I:L/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-250",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-3931",
  "document_distribution": "",
  "details": [
    "A flaw was found in Ceph-Rook. An attacker with root capabilities can escape the cgroup isolation and gain access to unauthorized information. This issue impacts confidentiality, integrity, and availability."
  ],
  "references": null
}